### ISSUE TITLE
Style the  ViewModel Editor

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-devtools-components#26]
There is a component called `<viewmodel-editor>` that wraps the `<json-tree-editor>`. Its demo page is at `viewmodel-editor/viewmodel-editor.html`.

It is mostly styled, except for the header and save button:

![image](https://user-images.githubusercontent.com/5851984/47458052-49eeee00-d79e-11e8-9d98-b82002223a96.png)

**Comment by justinbmeyer** [comment]
Should there be a save button?

**Comment by phillipskevin** [comment]
I think there should. You might want to add an item to a list and set several properties on it before saving. It's something we can keep in mind during user testing though.
