### ISSUE TITLE
Working with empty strings in the ViewModel Editor is strange

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-devtools-components#68]
Empty strings show up with a large space between them:

![image](https://user-images.githubusercontent.com/5851984/51351944-d5aca980-1a71-11e9-8c63-32f88c8e9b69.png)

...but the clickable area is really small:
![image](https://user-images.githubusercontent.com/5851984/51352014-055bb180-1a72-11e9-85e3-dc2266f009e2.png)

We should:
* remove this large space
* make it so you can edit strings by clicking on the quotation marks directly
* use normal quotation marks
* remove key/value pairs that are empty if you click outside of them, so you don't get this weird colon:

![image](https://user-images.githubusercontent.com/5851984/51352098-3805aa00-1a72-11e9-942e-12a9d1c394ab.png)

**Comment by ryangwilson** [comment]
We should also make the quotation marks unselectable - which was the reason I offset them originally
  

  
  

  
  
>
