### ISSUE TITLE
Add a Reset button to ViewModel Editor

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-devtools-components#69]
If you edit something in a ViewModel, there's no way to reset:

![image](https://user-images.githubusercontent.com/5851984/51352983-d98dfb00-1a74-11e9-811a-0a385574d272.png)

We should put a button next to the Apply button that lets you Reset.

**Comment by jamiemccue** [comment]
This one is pretty straight forward. I searched around for some similar patterns and found that using a 'reset' button is common. 

1. User makes an change and clicks "Applies Changes" 2. At which point a Reset button appears allowing the user to reset the changes. 

![Screen Shot 2019-10-29 at 11 34 19 AM](https://user-images.githubusercontent.com/381138/67798198-4ee51e00-fa40-11e9-9a23-00824dc1b2b4.png)

**Comment by phillipskevin** [comment]
A couple questions for you @jamiemccue:

1. Should we change the other button to just "Apply"? In devtools, there often isn't a lot of space for the buttons:

![image](https://user-images.githubusercontent.com/5851984/67879733-748b2980-fb0b-11e9-9a12-e091273216ae.png)

2. Currently, the "Apply Changes" button only appears when you have made a change in the editor that has not been applied:

![image](https://user-images.githubusercontent.com/5851984/67879816-98e70600-fb0b-11e9-927c-4a45cd5a77d7.png)
 
So I think the flow be: User makes a change and can then either hit "Reset" or "Apply". Does that make sense to you?

**Comment by justinbmeyer** [comment]
Makes sense to me

**Comment by bmomberger-bitovi** [comment]
Closed via #100
