### ISSUE TITLE
New JSON Editor

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-devtools-components#9]
We should replace the `jsoneditor` we're using with our own version that does just what we need.

The current version we're using has a few problems:
* in the `tree` view, it doesn't remember the expanded state  of objects/arrays after you call `setJSON` (since devtools updates the data every 100ms, this makes it pretty unusable)
* the `code` view might be difficult for new developers to work with since you have to know where to put commas/colons
* the styling could be better

We should build our own JSON Tree View with interactions similar to other places in Chrome Devtools.

The base view should look like the Watch panel:
![image](https://user-images.githubusercontent.com/5851984/41725633-ecf123c8-7535-11e8-9ce1-804b1a9ebcc8.png)

It should
- [x] Display each property on its own line
- [x] Show the Type for Objects/Arrays

![image](https://user-images.githubusercontent.com/5851984/41727302-a16d46bc-7539-11e8-80c6-901f3d04b065.png)

- [x] Have a `>` that lets you expand objects
- [x] Indent nested properties

![image](https://user-images.githubusercontent.com/5851984/41726654-37f50c3e-7538-11e8-97f1-68708747fcd8.png)

- [ ] Add new properties when you click into an object (but not on a key or value)
- [ ] "Prune" empty properties when you click outside the editor

![new-property](https://user-images.githubusercontent.com/5851984/41726695-549fcd88-7538-11e8-8558-1d009aacb0d8.gif)

- [x] Show a `-` next to each property on hover so you can delete it 

![image](https://user-images.githubusercontent.com/5851984/41725913-98c5eb34-7536-11e8-980d-02e06a30fdaa.png)

- [x] Show two `<input>` elements with a `:` between them for new properties:

![image](https://user-images.githubusercontent.com/5851984/41726017-d67393be-7536-11e8-8a3c-9f28f0a3ebb2.png)

- [x] Allow you to edit a key or value by clicking into them

![image](https://user-images.githubusercontent.com/5851984/41726094-02d6c2aa-7537-11e8-820e-8a887d72f92a.png)

- [x] Export a `getJSON` and `setJSON` function so we can easily integrate with the current `<viewmodel-editor>` component

**Comment by justinbmeyer** [comment]
I'd also like to make sure it can show the type for Objects like chrome dev tools:

```
address:  Address
```

**Comment by justinbmeyer** [comment]
One other thing that would be very nice ... is a `breakOnChange` button ... I just had this problem where a `color` property was changing unexpectedly, I figured out where it was happening by doing:

```js
team.on("color", function(){ can.queues.logStack(); debugger; }, "notify")
```

Allowing people to do this easily would be a huge win.

**Comment by phillipskevin** [comment]
> I'd also like to make sure it can show the type for Objects

Good Idea. I've added that. For now that will just show `Object` or `Array(<length>)` since we don't have the Type information.
